// Copyright 2018 Eryx <evorui аt gmail dοt com>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.19.4
// source: stats.proto

package hapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbStatsSampleFeed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind  string                `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Cycle uint32                `protobuf:"varint,2,opt,name=cycle,proto3" json:"cycle,omitempty"`
	Items []*PbStatsSampleEntry `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *PbStatsSampleFeed) Reset() {
	*x = PbStatsSampleFeed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbStatsSampleFeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbStatsSampleFeed) ProtoMessage() {}

func (x *PbStatsSampleFeed) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbStatsSampleFeed.ProtoReflect.Descriptor instead.
func (*PbStatsSampleFeed) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0}
}

func (x *PbStatsSampleFeed) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PbStatsSampleFeed) GetCycle() uint32 {
	if x != nil {
		return x.Cycle
	}
	return 0
}

func (x *PbStatsSampleFeed) GetItems() []*PbStatsSampleEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

type PbStatsSampleEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Items []*PbStatsSampleValue `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *PbStatsSampleEntry) Reset() {
	*x = PbStatsSampleEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbStatsSampleEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbStatsSampleEntry) ProtoMessage() {}

func (x *PbStatsSampleEntry) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbStatsSampleEntry.ProtoReflect.Descriptor instead.
func (*PbStatsSampleEntry) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{1}
}

func (x *PbStatsSampleEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PbStatsSampleEntry) GetItems() []*PbStatsSampleValue {
	if x != nil {
		return x.Items
	}
	return nil
}

type PbStatsSampleValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time  uint32 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Value int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PbStatsSampleValue) Reset() {
	*x = PbStatsSampleValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbStatsSampleValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbStatsSampleValue) ProtoMessage() {}

func (x *PbStatsSampleValue) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbStatsSampleValue.ProtoReflect.Descriptor instead.
func (*PbStatsSampleValue) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{2}
}

func (x *PbStatsSampleValue) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *PbStatsSampleValue) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type PbStatsIndexList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IndexCycle  uint32              `protobuf:"varint,1,opt,name=index_cycle,json=indexCycle,proto3" json:"index_cycle,omitempty"`
	SampleCycle uint32              `protobuf:"varint,2,opt,name=sample_cycle,json=sampleCycle,proto3" json:"sample_cycle,omitempty"`
	Items       []*PbStatsIndexFeed `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *PbStatsIndexList) Reset() {
	*x = PbStatsIndexList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbStatsIndexList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbStatsIndexList) ProtoMessage() {}

func (x *PbStatsIndexList) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbStatsIndexList.ProtoReflect.Descriptor instead.
func (*PbStatsIndexList) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{3}
}

func (x *PbStatsIndexList) GetIndexCycle() uint32 {
	if x != nil {
		return x.IndexCycle
	}
	return 0
}

func (x *PbStatsIndexList) GetSampleCycle() uint32 {
	if x != nil {
		return x.SampleCycle
	}
	return 0
}

func (x *PbStatsIndexList) GetItems() []*PbStatsIndexFeed {
	if x != nil {
		return x.Items
	}
	return nil
}

type PbStatsIndexFeed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time  uint32                `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Items []*PbStatsSampleEntry `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *PbStatsIndexFeed) Reset() {
	*x = PbStatsIndexFeed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbStatsIndexFeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbStatsIndexFeed) ProtoMessage() {}

func (x *PbStatsIndexFeed) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbStatsIndexFeed.ProtoReflect.Descriptor instead.
func (*PbStatsIndexFeed) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{4}
}

func (x *PbStatsIndexFeed) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *PbStatsIndexFeed) GetItems() []*PbStatsSampleEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_stats_proto protoreflect.FileDescriptor

var file_stats_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68,
	0x61, 0x70, 0x69, 0x22, 0x6d, 0x0a, 0x11, 0x50, 0x62, 0x53, 0x74, 0x61, 0x74, 0x73, 0x53, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x46, 0x65, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x79, 0x63,
	0x6c, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x62, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x22, 0x58, 0x0a, 0x12, 0x50, 0x62, 0x53, 0x74, 0x61, 0x74, 0x73, 0x53, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x61,
	0x70, 0x69, 0x2e, 0x50, 0x62, 0x53, 0x74, 0x61, 0x74, 0x73, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x3e, 0x0a, 0x12,
	0x50, 0x62, 0x53, 0x74, 0x61, 0x74, 0x73, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x84, 0x01, 0x0a,
	0x10, 0x50, 0x62, 0x53, 0x74, 0x61, 0x74, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x63, 0x79, 0x63, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x43, 0x79, 0x63,
	0x6c, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x63, 0x79, 0x63,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x43, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x62, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x46, 0x65, 0x65, 0x64, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x22, 0x56, 0x0a, 0x10, 0x50, 0x62, 0x53, 0x74, 0x61, 0x74, 0x73, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x46, 0x65, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x61, 0x70,
	0x69, 0x2e, 0x50, 0x62, 0x53, 0x74, 0x61, 0x74, 0x73, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x2e,
	0x3b, 0x68, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stats_proto_rawDescOnce sync.Once
	file_stats_proto_rawDescData = file_stats_proto_rawDesc
)

func file_stats_proto_rawDescGZIP() []byte {
	file_stats_proto_rawDescOnce.Do(func() {
		file_stats_proto_rawDescData = protoimpl.X.CompressGZIP(file_stats_proto_rawDescData)
	})
	return file_stats_proto_rawDescData
}

var file_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_stats_proto_goTypes = []interface{}{
	(*PbStatsSampleFeed)(nil),  // 0: hapi.PbStatsSampleFeed
	(*PbStatsSampleEntry)(nil), // 1: hapi.PbStatsSampleEntry
	(*PbStatsSampleValue)(nil), // 2: hapi.PbStatsSampleValue
	(*PbStatsIndexList)(nil),   // 3: hapi.PbStatsIndexList
	(*PbStatsIndexFeed)(nil),   // 4: hapi.PbStatsIndexFeed
}
var file_stats_proto_depIdxs = []int32{
	1, // 0: hapi.PbStatsSampleFeed.items:type_name -> hapi.PbStatsSampleEntry
	2, // 1: hapi.PbStatsSampleEntry.items:type_name -> hapi.PbStatsSampleValue
	4, // 2: hapi.PbStatsIndexList.items:type_name -> hapi.PbStatsIndexFeed
	1, // 3: hapi.PbStatsIndexFeed.items:type_name -> hapi.PbStatsSampleEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_stats_proto_init() }
func file_stats_proto_init() {
	if File_stats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbStatsSampleFeed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbStatsSampleEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbStatsSampleValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbStatsIndexList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbStatsIndexFeed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stats_proto_goTypes,
		DependencyIndexes: file_stats_proto_depIdxs,
		MessageInfos:      file_stats_proto_msgTypes,
	}.Build()
	File_stats_proto = out.File
	file_stats_proto_rawDesc = nil
	file_stats_proto_goTypes = nil
	file_stats_proto_depIdxs = nil
}
